---
language: python
sudo: false

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - ansible --version

  # set roles_path so we can find the role under test
  - printf '[defaults]\nroles_path=../..' > ansible.cfg

script:
  # Syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run the role
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --become

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
