---
language: python
cache: pip
sudo: required

install:
  - pip install ansible
  - ansible --version

script:
  - ansible-playbook "tests/$PLAYBOOK" --inventory tests/inventory --syntax-check
  - ansible-playbook "tests/$PLAYBOOK" --inventory tests/inventory --connection=local --become
  - >
    ansible-playbook tests/$PLAYBOOK -i tests/inventory --connection=local --become
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - cd tests
  - bundle install
  - bundle exec rake

matrix:
  include:
  - env: ANSIBLE_ROLES_PATH=.. PLAYBOOK=playbook-2.4.5.yml
  - env: ANSIBLE_ROLES_PATH=.. PLAYBOOK=playbook-2.5.3.yml
  - env: ANSIBLE_ROLES_PATH=.. PLAYBOOK=playbook-2.6.0.yml
  - env: ANSIBLE_ROLES_PATH=.. PLAYBOOK=playbook-2.7.0.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
