---
language: python
sudo: false

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - ansible --version
  - mkdir roles
  - ln -s $PWD roles/ruby
  #- printf '[defaults]\nroles_path=roles' > ansible.cfg

env:
  ANSIBLE_ROLES_PATH=roles

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --become

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
