---
language: python
sudo: required

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - ansible --version

env:
  ANSIBLE_ROLES_PATH=..

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --become
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local --become
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
