---
language: python
cache: pip
sudo: required

install:
  - pip install ansible
  - ansible --version

script:
  - ansible-playbook "tests/$PLAYBOOK" -i tests/inventory --syntax-check
  - ansible-playbook "tests/$PLAYBOOK" -i tests/inventory --connection=local --become
  - cd tests
  - bundle install
  - bundle exec rake

matrix:
  include:
  - env: ANSIBLE_ROLES_PATH=.. PLAYBOOK=playbook-2.4.5.yml
  - env: ANSIBLE_ROLES_PATH=.. PLAYBOOK=playbook-2.5.3.yml
  - env: ANSIBLE_ROLES_PATH=.. PLAYBOOK=playbook-2.6.0.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
