- name: Prerequisite software is installed
  apt:
    update_cache: yes
    name:
      - autoconf
      - build-essential
      - libffi-dev
      - libreadline-dev
      - libssl-dev
      - libyaml-dev
      - openssl
      - zlib1g
      - zlib1g-dev
    state: present
  become: true
  tags: apt,ruby

- name: Ruby tarball is downloaded
  get_url:
    url: "https://cache.ruby-lang.org/pub/ruby/{{ ruby_version.major }}.{{ ruby_version.minor }}/ruby-{{ ruby_version_full }}.tar.gz"
    dest: "/tmp/ruby-{{ ruby_version_full }}.tar.gz"
  tags: ruby

- name: Ruby tarball is unpacked
  unarchive:
    src: "/tmp/ruby-{{ ruby_version_full }}.tar.gz"
    dest: /usr/local/src
    remote_src: yes
  become: true
  tags: ruby

- name: Ruby is configured
  command: |
          ./configure
          --enable-shared
          --disable-install-doc
          --disable-install-rdoc
          --disable-install-capi
  args:
    chdir: /usr/local/src/ruby-{{ ruby_version_full }}
  become: true
  tags: ruby

- name: Ruby is built
  make:
    chdir: /usr/local/src/ruby-{{ ruby_version_full }}
  become: true
  tags: ruby,make

- name: Ruby is installed
  make:
    chdir: /usr/local/src/ruby-{{ ruby_version_full }}
    target: install
  become: yes
  tags: ruby,make

- name: .installed.list is preserved for later uninstall
  copy:
    src: /usr/local/src/ruby-{{ ruby_version_full }}/.installed.list
    dest: /usr/local/src/ruby-{{ ruby_version_full }}-installed.list
    remote_src: yes
  become: true
  tags: ruby

- name: Ruby sources are gone
  file:
    path: "/usr/local/src/ruby-{{ ruby_version_full }}"
    state: absent
  become: true
  tags: ruby,cleanup

- name: Ruby tarball is not present anymore
  file:
    path: "/tmp/ruby-{{ ruby_version_full }}.tar.gz"
    state: absent
  become: true
  tags: ruby,cleanup
