- name: "Get Ruby version"
  command: "/usr/local/bin/ruby -e 'puts RUBY_VERSION'"
  changed_when: false
  register: ruby_version_present
  ignore_errors: true

- name: Uninstall the current Ruby if it is not the desired Ruby version
  include: tasks/uninstall.yml
  when: " ( ruby_version_present | succeeded ) and ('{{ruby_version_full}}' not in ruby_version_present.stdout) "

- name: Install the desired Ruby version
  include: tasks/install.yml
  when: " ( ruby_version_present | failed ) or ('{{ruby_version_full}}' not in ruby_version_present.stdout) "

- name: Assert that the present ruby version is equal to the desired {{ ruby_version_full }}
  command: /usr/local/bin/ruby -e "exit '{{ ruby_version_full }}' == RUBY_VERSION"
  register: command_result
  changed_when: command_result.rc != 0
  ignore_errors: no
  tags: ruby

- name: Install latest bundler gem
  gem:
    name: bundler
    user_install: no
    state: latest
  tags: ruby,gem,bundler

- name: Set global gem options
  copy:
    src: etc/gemrc
    dest: /etc/gemrc
    owner: root
    group: root
    mode: 0644
  tags: ruby,gem

- name: Add gem user_dir to PATH
  copy:
    src: etc/profile.d/gem-user_dir-path.sh
    dest: /etc/profile.d/gem-user_dir-path.sh
    owner: root
    group: root
    mode: 0644
  tags: ruby,gem
