- name: Check if any ruby is present
  command: test -x /usr/local/bin/ruby
  ignore_errors: yes
  register: ruby_present
  tags: ruby

- name: Get what version of ruby is present
  command: "/usr/local/bin/ruby -e 'puts RUBY_VERSION'"
  when: ruby_present|succeeded
  register: ruby_version_present



- name: Install the desired Ruby version
  include: tasks/install.yml
  when: ruby_present|failed or ruby_version_present|skipped

- name: Install latest bundler gem
  gem:
    name: bundler
    user_install: no
    state: latest
  tags: ruby,gem,bundler

- name: Set global gem options
  copy:
    src: etc/gemrc
    dest: /etc/gemrc
    owner: root
    group: root
    mode: 0644
  tags: ruby,gem

- name: Add gem user_dir to PATH
  copy:
    src: etc/profile.d/gem-user_dir-path.sh
    dest: /etc/profile.d/gem-user_dir-path.sh
    owner: root
    group: root
    mode: 0644
  tags: ruby,gem

- name: Verify that the present ruby version is equal to the desired {{ ruby_version_full }}
  command: /usr/local/bin/ruby -e "exit '{{ ruby_version_full }}' == RUBY_VERSION"
  ignore_errors: no
  tags: ruby
