# frozen_string_literal: true

source 'https://rubygems.org'

group :development, :test do
  gem 'bundler'
  gem 'guard-bundler'
  gem 'guard-rspec', require: false
  gem 'pry'
  gem 'pry-byebug'
  gem 'rake'
  gem 'rb-readline'
  gem 'rspec'
  gem 'rubocop'
  gem 'terminal-notifier'
  gem 'terminal-notifier-guard'
end
