require 'pathname'
project_name = Pathname(__dir__).parent.realpath.basename.to_s

Vagrant.configure('2') do |config|
  config.vm.provider 'virtualbox' do |v|
    v.cpus = 2
  end

  config.vm.define("#{project_name}_debian") do |machine|
    machine.vm.box = 'debian/jessie64'

    machine.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'playbook.yml'
      ansible.galaxy_roles_path = '../..'
      ansible.compatibility_mode = '2.0'
    end
  end

  config.vm.define("#{project_name}_ubuntu") do |machine|
    machine.vm.box = 'ubuntu/bionic64'

    machine.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'playbook.yml'
      ansible.galaxy_roles_path = '../..'
      ansible.compatibility_mode = '2.0'
      ansible.extra_vars = { ansible_python_interpreter: '/usr/bin/python3' }
    end
  end
end
