#!/usr/bin/env ruby
# frozen_string_literal: true
$LOAD_PATH.unshift File.join(__dir__, '..', 'lib')
require 'fileutils'
require 'vagrant/environment'

vagrant = Vagrant::Environment.new

vagrant.vms.each do |vm|
  vm.restore_or_create_snapshot('2.4.1')

  # Backwards compatibility test: Change Ruby 2.4.0 to 2.2.6
  FileUtils.cp('playbook-2.2.6.yml', 'playbook.yml')
  vm.provision
  vm.restore_or_create_snapshot('2.2.6')

  # Forward compatibility test: Change Ruby 2.2.6 to 2.3.3
  FileUtils.cp('playbook-2.3.3.yml', 'playbook.yml')
  vm.provision
  vm.restore_or_create_snapshot('2.3.3')
end
